/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.mestobo;

import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;

class MestoboTest {
	@Test
	void testAppCreation() {
		Mestobo classUnderTest = new Mestobo();
		assertNotNull(classUnderTest);
	}
}
